/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkExperienceIndexRouteImport } from './routes/work-experience.index'
import { Route as PersonalBlogIndexRouteImport } from './routes/personal-blog.index'
import { Route as DemoProjectsIndexRouteImport } from './routes/demo-projects.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkExperienceIndexRoute = WorkExperienceIndexRouteImport.update({
  id: '/work-experience/',
  path: '/work-experience/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalBlogIndexRoute = PersonalBlogIndexRouteImport.update({
  id: '/personal-blog/',
  path: '/personal-blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoProjectsIndexRoute = DemoProjectsIndexRouteImport.update({
  id: '/demo-projects/',
  path: '/demo-projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/demo-projects/': typeof DemoProjectsIndexRoute
  '/personal-blog/': typeof PersonalBlogIndexRoute
  '/work-experience/': typeof WorkExperienceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/about': typeof AboutIndexRoute
  '/blog': typeof BlogIndexRoute
  '/demo-projects': typeof DemoProjectsIndexRoute
  '/personal-blog': typeof PersonalBlogIndexRoute
  '/work-experience': typeof WorkExperienceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/demo-projects/': typeof DemoProjectsIndexRoute
  '/personal-blog/': typeof PersonalBlogIndexRoute
  '/work-experience/': typeof WorkExperienceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/$slug'
    | '/about/'
    | '/blog/'
    | '/demo-projects/'
    | '/personal-blog/'
    | '/work-experience/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$slug'
    | '/about'
    | '/blog'
    | '/demo-projects'
    | '/personal-blog'
    | '/work-experience'
  id:
    | '__root__'
    | '/'
    | '/blog/$slug'
    | '/about/'
    | '/blog/'
    | '/demo-projects/'
    | '/personal-blog/'
    | '/work-experience/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogSlugRoute: typeof BlogSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DemoProjectsIndexRoute: typeof DemoProjectsIndexRoute
  PersonalBlogIndexRoute: typeof PersonalBlogIndexRoute
  WorkExperienceIndexRoute: typeof WorkExperienceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-experience/': {
      id: '/work-experience/'
      path: '/work-experience'
      fullPath: '/work-experience/'
      preLoaderRoute: typeof WorkExperienceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-blog/': {
      id: '/personal-blog/'
      path: '/personal-blog'
      fullPath: '/personal-blog/'
      preLoaderRoute: typeof PersonalBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-projects/': {
      id: '/demo-projects/'
      path: '/demo-projects'
      fullPath: '/demo-projects/'
      preLoaderRoute: typeof DemoProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogSlugRoute: BlogSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  DemoProjectsIndexRoute: DemoProjectsIndexRoute,
  PersonalBlogIndexRoute: PersonalBlogIndexRoute,
  WorkExperienceIndexRoute: WorkExperienceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
